version: '3'

services:
  continuous_double_auction:
    image: project
    build: .
    ports:
      - '8082:8090'
    networks:
      exchange:
        ipv4_address: 10.10.0.2
  client:
    image: project
    ports:
      - '8083:8090'
    environment:
      - SERVER_NAME="exchange"
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLIENT_PORT="8090"
    depends_on:
      - continuous_double_auction
    networks:
      exchange:
        ipv4_address: 10.10.0.3
  client_2:
    image: project
    ports:
      - '8084:8090'
    environment:
      - SERVER_NAME="exchange"
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLIENT_PORT="8090"
    depends_on:
      - continuous_double_auction
    networks:
      exchange:
        ipv4_address: 10.10.0.4

networks:
  exchange:
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/16"


