version: '3.4'

services:
  continuous_double_auction:
    image: project
    build: .
    ports:
      - '8082:8090'
    networks:
      exchange:
        ipv4_address: 10.10.0.2
  client_0:
    image: project
    ports:
      - '8083:8090'
    env_file:
       - 'variables.env'
    depends_on:
      - continuous_double_auction
    networks:
      exchange:
        ipv4_address: 10.10.0.3
  client_1:
    image: project
    ports:
      - '8084:8090'
    env_file:
       - 'variables.env'
    depends_on:
      - continuous_double_auction
    networks:
      exchange:
        ipv4_address: 10.10.0.4
  react_app:
    image: app
    ports:
      - '5173:5173'
    depends_on:
      - client_0
    environment:
        - REACT_APP_API_URL=http://backend_user2:5000/api
    networks:
      exchange:
        ipv4_address: 10.10.0.10
networks:
  exchange:
    ipam:
      config:
        - subnet: 10.10.0.0/24
